# Site settings
title: Ludovic - Program and Thinks !
email: noemail
description: > # this means to ignore newlines until "baseurl:"
  Yet again a blog about technologies... Hum, or exactly what I see in them,
  experimentations, love/hate and so one, with a LoL spirit of course.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000/" # the base hostname & protocol for your site
twitter_username: ludovic_deluna
github_username:  ludovicdeluna
version: "1.0"
github:
  repo : "https://github.com/ludovicdeluna/myblog"

# Server setting
port: 4000
host: localhost
encoding: utf-8

# Pagination
paginate: 3
paginate_path: "blog/page:num/"

# FrontMatter default settings
defaults:
  -
    scope:
      type: "posts"
    values:
      permalink: "/:categories/:year/:month/:day/:title/"
      excerpt_separator: "<!--more-->"

# Build settings
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: redcarpet
redcarpet:
  extensions: ["tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "with_toc_data"]
